### ISSUE TITLE
output POSCAR_unitcell has different order than lammps input

### ISSUE THREAD

**Issue by alexgorfer** [abelcarreras/phonolammps#12]
Hi,
I am working with a very large unitcell and I think already when we load the lammps input with get_structure_from_lammps() the order in which lmp.extract_atom() returns the properties gets jumbled around, which gives a strange -c POSCAR_unitcell.

More precise this is the head of the starting POSCAR:
```
# Alkali Feldspar
1.000000
      8.33702216        0.00000000        0.00000000
      0.56917101       12.96851226        0.00000000
     -3.19090160       -0.33935163        6.51281770
 O  Na  Al  Si
    32       4       4      12
```
which I then transform into a lammps configuration with the same order (first 32 are type 1, then 4 type 2 etc..). After using phonolammps with -c POSCAR_unitcell I get
```
Generated using phonoLAMMPS
1.0
        8.3370221600         0.0000000000         0.0000000000
        0.5691710100        12.9685122600         0.0000000000
       -3.1909016000        -0.3393516300         6.5128177000
O Na Al Si O Si 
27 4 4 10 5 2
```
The file is consistent with FORCE_CONSTANT and I get the correct bands and everything from phonopy, however I cant use the FORCE_CONSTANTs with dynaphopy since `dynaphopy POSCAR_unitcell --dim 2 2 2 -c_lammps LAMMPS.lammpstrj`  does not give a supercell that has the right phonopy-FORCE_CONSTANT  order.

I have a fix in mind and wanted to ask you if its ok to add the lines in bold to iofile.py:
<pre>
def get_structure_from_lammps(..)
    ...
    type_mass = lmp.extract_atom("mass", 2)
    type = lmp.extract_atom("type", 0)

    masses = np.array([type_mass[type[i]] for i in range(na)], dtype=float)
    symbols = [mass_to_symbol(masses[i]) for i in range(na)]

    xp = lmp.extract_atom("x", 3)
    positions = np.array([[xp[i][0], xp[i][1], xp[i][2]] for i in range(na)], dtype=float)
    <b>
    id = lmp.extract_atom("id", 0)
    id = np.array([id[i]-1 for i in range(na)], dtype=int)

    positions = positions[id.argsort()]
    symbols = [symbols[i] for i in id.argsort()]
    masses = masses[id.argsort()]
   </b>
    return PhonopyAtoms(positions=positions,
                        masses=masses,
                        symbols=symbols,
                        cell=unitcell)
</pre>
So I force the order to be the same as the ids. I think the def get_forces() are not affected by this!?
From my experiments, I do get the same order as my input and the FORCE_CONSTANTS and POSCAR_unitcell seem consitent as i get same band.png as before. But do you think this is ok or will it mess something up?

Thanks in advance,
Alex

**Comment by abelcarreras** [comment]
Hi @alexgorfer,  thanks for your bug report.

You are right, changing the order of atoms in *get_structure_from_lammps* function should not affect other parts of the code. I think it is very good idea to use atoms ID order in PhonopyAtoms object, this way it will be consistent with the input. I will include your proposal to the code.

thanks again

**Comment by alexgorfer** [comment]
Hi @abelcarreras, ah ok awesome! Happy to help!
