### ISSUE TITLE
The maximum size of a unit cell

### ISSUE THREAD

**Issue by yuzc22** [abelcarreras/phonolammps#16]
Dear author，
Thank you for sharing this nice tool. I am trying to use the machine learning potential function I have trained to calculate the phonon spectrum of a supercell. My structure is a unit cell containing 10000 atoms. I find that there will be errors at this time. Is there any restriction on phonolammps in this respect?
Kind regards,
yzc

**Comment by abelcarreras** [comment]
Hi @yuzc22,

In principle there are not restrictions in the size of the supercell or space group. If you get wrong results is either a bug of the code or a problem in the MD.

**Comment by yuzc22** [comment]
Hi,
Thank you very much for your reply! I did some tests and found that it would be fine if I had a few hundred atoms per unit cell, if it was thousands, it would be killed, if there were more atoms, there would be an error in the picture. 
 Of course, it is probably because of my configuration of the environment, I am not proficient in this area. Perhaps you can see from my error where there is a mistake in the configuration of the environment and give some suggestions to correct it? Thank you again for your careful reply.
Thank you very much for your reply! I did some tests and found that it would be fine if I had a few hundred atoms per unit cell, if it was thousands, it would be killed, if there were more atoms, there would be an error in the picture. 
 Of course, it is probably because of my configuration of the environment, I am not proficient in this area. Perhaps you can see from my error where there is a mistake in the configuration of the environment and give some suggestions to correct it? Thank you again for your careful reply.
![question](https://github.com/abelcarreras/phonolammps/assets/143714046/100c6e8c-aa8f-4f93-a23b-25d512aaf384)

**Comment by abelcarreras** [comment]
Well, as the size increases it will be an increase on memory requirements as well. You might be hitting this limit.
One thing you can try is to use —logshow option to check if there is any problem with lammps calculation.
