### ISSUE TITLE
how to link phonolammps to a specific lammps executable?

### ISSUE THREAD

**Issue by zhangxiaoyu2046** [abelcarreras/phonolammps#17]
Hi developer,
I want to install phonolammps with a specific version of lammps: https://github.com/sekocha/lammps-polymlp-package
I have successfully install the lammps-polymlp, and it works properly.

Now I want to link it with phonolammps, but I don't know how to specify the lammps path in phonolammps.
The installation manual tells me to: python setup.py install --user --prefix=
but where can I configure the location of my lammps package?

P.S. I had successfully installed phonolammps before like this:
1. conda create -n phonolammps -c conda-forge
2. source activate phonolammps
3. conda install lammps
4. install phonolammps by: python setup.py install --user

Is there a similar way to install a new phonolammps with polymlp?
Thanks in advance.

**Comment by abelcarreras** [comment]
Hi, phonolammps only requires LAMMPS Python API to be installed alongside LAMMPS. There is no path to find LAMMPS because phonolammps just needs to run in environment where lammps python module is accessible.
