### ISSUE TITLE
Does phonolammps supports parallel calculation?

### ISSUE THREAD

**Issue by JTaozhang** [abelcarreras/phonolammps#19]
Hi Abel,

First I would like to thank you for making such nice software. Currently, I am calculating the force constants of large system containing about 5000 atoms. I am worried about the speed of calculation. So, I wonder that whether phonolammps supports parallel calculation to accelerate the calculation speed ?

Best,
Tao

**Comment by abelcarreras** [comment]
Hi @JTaozhang, sorry for this late response. phonolammps interfaces with phonopy for all the heavy lifting. As far as I know phonopy is written with openMP so it supports parallel calculation, but it may depend on your installation (compilation).
