### ISSUE TITLE
primitive cell and group of atoms

### ISSUE THREAD

**Issue by Movaffaq** [abelcarreras/phonolammps#2]
Dear Abel Carreras
Thank you for sharing this nice tool. I am trying to study an interface between two materials with the same lattice-type. My system is relatively large because I want to see epitaxial strain at the interface vanishes away from interface. First, please help me to understand how to define the primitive cell? because right now I got a huge number of modes which I do not understand. Second, Is it possible to calculate the force constant for a large system then plot modes for a group of atoms e.g. a few monolayers around the interface?
Kind regards,
mk

**Comment by abelcarreras** [comment]
Dear @Movaffaq, in a system like this the straightforward way would be to define a long unitcell that include two interfaces and both materials to create a minimum symmetric unit (It is difficult to explain without a picture, something like:  M1 - Interface - M2 - interface - M1). The length of M1 and M2 will depend on the influence of the interface to the bulk.
Regarding your second question you can calculate a partial density of states (DOS). That is separate the DOS in contributions for each chemical element.  For this you will have to use phonopy using the force constants calculated with phonolammps. If you want more control I guess you can use phonopy python API and make a script to do it, I don't know if any other code exists already to do this.
