### ISSUE TITLE
About how to use phonolammps on molecular crystal,such as ice Ih crystal

### ISSUE THREAD

**Issue by ChengyangYuan** [abelcarreras/phonolammps#3]
Hi, Thank you for offering such nice code. Here I got some trouble when using phonolammps. I want to use this code to generate 2nd force constant for hexagonal ice (ice Ih,which is a good model for molecular crystal) and then study the phonon dispersion. But when I prepared the lammps input file (in.lammps) and structure data file of ice Ih, then used the command line interface and "phonolammps in.lammps --dim 2 2 2  -c POSCAR_unitcell -p" to run, nothing happened. No error information, no POSCAR files were generated. But when I run the example in the example file, everything is Ok. So I wonder if phonolammps supports the calculation for molecular systems or it can only be used for atomic systems. Please give me an answer. Thank you very much.

**Comment by abelcarreras** [comment]
Hi @ChengyangYuan,
Maybe something wrong with the LAMMPS calculation.
Have you tried to use --logshow option to see the contents of LAMMPS calculations log?
Maybe this will give you some insights on what is going wrong.

**Comment by abelcarreras** [comment]
In principle you can use phonoLAMMPS for any kind of crystal.

**Comment by ChengyangYuan** [comment]
Thank you for your reply! I will follow your advice and check my lammps file as well as log messages. Since you say the code is suitable for any crystals. I believe I must have some errors.

Anyway, thank you and hope you have a good day.



-----原始邮件-----
发件人:"Abel Carreras" <notifications@github.com>
发送时间:2020-08-26 20:38:36 (星期三)
收件人: abelcarreras/phonolammps <phonolammps@noreply.github.com>
抄送: ChengyangYuan <yuanchengyang@mail.dlut.edu.cn>, Mention <mention@noreply.github.com>
主题: Re: [abelcarreras/phonolammps] About how to use phonolammps on molecular crystal,such as ice Ih crystal (#3)






In principle you can use phonoLAMMPS for any kind of crystal.
