### ISSUE TITLE
Unable to run examples

### ISSUE THREAD

**Issue by Appalakondaiah** [abelcarreras/phonolammps#4]
Dear Abel,

I have recently started Phonons with Lammps and install lammps and phonolammps.

While running the example files, I am struck with the below error
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted (core dumped)

Can you suggest to me some starting points use phonolammps..

Regards
Kondaiah

**Comment by abelcarreras** [comment]
Dear Kondaiah,

This seems related to LAMMPS library. Have you checked that
your LAMMPS python API works correctly?
I have tested for 16 March 2018, 15 May 2019 and 18 Sep 2020 versions.
For other versions of LAMMPS I can't guarantee.

**Comment by Appalakondaiah** [comment]
Dear Abel,

Yes..My lammps version is 18th Sep 2020 and working API also

**Comment by Appalakondaiah** [comment]
Dear Dr. Abel,

To my understanding, I am missing the process of computing the FORCE_CONSTANT file.

Can you please suggest to me the process to compute the Finite-displacement method in LAMMPS?

with regards
Kondaiah

**Comment by abelcarreras** [comment]
Dear Kondaiah,

I don't understand very well what you mean. 
Can you be more specific on the issue you are having?
Maybe something that I can use to reproduce it.
