### ISSUE TITLE
Problem of running Phonolammps

### ISSUE THREAD

**Issue by JWCheys** [abelcarreras/phonolammps#5]
Dear Abel,
When I try to perform Phonolammps to calculate force constants, I got the following errors:
Traceback (most recent call last):

  **File "/home/yuzhouweijia/cjw/software/library/Anaconda/bin/phonolammps", line 86, in <module>
    symmetrize=not(args.no_symmetrize))
  File "/home/yuzhouweijia/cjw/software/library/Anaconda/lib/python3.7/site-packages/phonolammps/__init__.py", line 260, in __init__
    self._structure = get_structure_from_lammps(self._lammps_commands_list)
  File "/home/yuzhouweijia/cjw/software/library/Anaconda/lib/python3.7/site-packages/phonolammps/iofile.py", line 101, in get_structure_from_lammps
    xlo =lmp.extract_global("boxxlo", 1)
  File "/home/yuzhouweijia/cjw/software/library/lammps-29Oct20/python/lammps.py", line 867, in extract_global
    return target_type(ptr[0])
UnboundLocalError: local variable 'target_type' referenced before assignment**

I confirm LAMMPS has been built as a library of Python, because I have successfully tested several examples. At present, My LAMMPS version is lammps-29Oct2020. In addition, I found that the above errors do not occur when using older versions of lammps, e.g. lammps-5Jun19. So, I'm confused whether this is a problem with the LAMMPS or with the Phonolammps. I would like to seek some help from you. Thanks very much!
Best regards,
Junwei Che

**Comment by abelcarreras** [comment]
Dear Junwei Che,

Is it possible that you are running an old version of phonoLAMMPS? Compatibility to LAMMPS 29Oct2020 version was added recently to phonolammps v0.7.1.

**Comment by JWCheys** [comment]
Dear Abel,
I am very grateful for your kind help and guidance.
Best wishes,
Junwei Che
