### ISSUE TITLE
How does lammps calculate the second- and third -order constants using the finite displacement method?

### ISSUE THREAD

**Issue by LANHNU** [abelcarreras/phonolammps#7]
I have generated the potential function model by deepmd. I currently intend to generate the second and third order force constants by "dp+lammps" and use the tiny displacement method. The purpose of this is to compare the results with the second and third order force constants calculated by VASP to verify the goodness of the potential function model generated by dp.

**Comment by abelcarreras** [comment]
I guess you mean phonoLAMMPS.
phonolammps uses phonopy to compute the 2nd order force constants. For this, it uses phonopy API to generate a set supercells with displacements according to the unit cell symmetry. Then, phonoLAMMPS interfaces with LAMMPS via LAMMPS python API to compute the atomic forces for each supercell. Finally, these forces are passed back to phonopy to compute the force constants.

**Comment by LANHNU** [comment]
您好，您的信件我已收到~This is an automatic reply, confirming that your e-mail was received.Thank you

**Comment by LANHNU** [comment]
您好，您的信件我已收到~This is an automatic reply, confirming that your e-mail was received.Thank you
