### ISSUE TITLE
Calculate FORCE_CONSTANTS goes wrong with phonolammps

### ISSUE THREAD

**Issue by maverick422** [abelcarreras/phonolammps#8]
PHONOLAMMPS: 0.8.3
LAMMPS: 29 September 2021
PHONOPY: 2.16.2
PYTHON: 3.9.7 (default, Sep 16 2021, 13:09:58)
DeePMD-kit v2.1.0

here is my input 
`    

    units           metal    
    box    tilt large
    boundary        p p p
    atom_style      atomic
    read_data       data.after
    pair_style      deepmd graph.002.pb                                              
    pair_coeff      * * 
    neighbor        0.3 bin
`

here is part  of the FORCE_CONSTANTS 

`
1 1
    -0.000000000000000    -0.000000000000000    -0.000000000000000
    -0.000000000000000    -0.000000000000000    -0.000000000000000
    -0.000000000000000    -0.000000000000000    -0.000000000000000
1 2
    -0.000000000000000    -0.000000000000000    -0.000000000000000
    -0.000000000000000    -0.000000000000000    -0.000000000000000
    -0.000000000000000    -0.000000000000000    -0.000000000000000
1 3
    -0.000000000000000    -0.000000000000000    -0.000000000000000
    -0.000000000000000    -0.000000000000000    -0.000000000000000
    -0.000000000000000    -0.000000000000000    -0.000000000000000
1 4
    -0.000000000000000    -0.000000000000000    -0.000000000000000
    -0.000000000000000    -0.000000000000000    -0.000000000000000
    -0.000000000000000    -0.000000000000000    -0.000000000000000
1 5
    -0.000000000000000    -0.000000000000000    -0.000000000000000
    -0.000000000000000    -0.000000000000000    -0.000000000000000
    -0.000000000000000    -0.000000000000000    -0.000000000000000
1 6
    -0.000000000000000    -0.000000000000000    -0.000000000000000
    -0.000000000000000    -0.000000000000000    -0.000000000000000
    -0.000000000000000    -0.000000000000000    -0.000000000000000
1 7
    -0.000000000000000    -0.000000000000000    -0.000000000000000
    -0.000000000000000    -0.000000000000000    -0.000000000000000
    -0.000000000000000    -0.000000000000000    -0.000000000000000
1 8
    -0.000000000000000    -0.000000000000000    -0.000000000000000
    -0.000000000000000    -0.000000000000000    -0.000000000000000
    -0.000000000000000    -0.000000000000000    -0.000000000000000
1 9
    -0.000000000000000    -0.000000000000000    -0.000000000000000
    -0.000000000000000    -0.000000000000000    -0.000000000000000
    -0.000000000000000    -0.000000000000000    -0.000000000000000
`

I would be grateful if you could help me!
[Uploading FORCE_CONSTANTS.txt…]()

**Comment by abelcarreras** [comment]
Thank you for reporting this issue.
Is this an issue with this particular potential or a general thing?
Have you tried to run some of the phonolammps examples?
If the issue appears only using this potential I will need all files and detailed instructions to reproduce the issue in a minimal example.

**Comment by abelcarreras** [comment]
Hi @maverick422, it has been a long time without a reply. If you still have the issue I will need some additional information about how to reproduce the bug (see previous comment). If not, I will close this issue.
